[project]
name = "backend-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.10",
    "ruff>=0.11.8",
]

[tool.ruff.format]
quote-style = "single"